import type { MpExpenditureReportItem } from 'api-definitions/MpExpenditureReport';

export const mockExpenditureReports: MpExpenditureReportItem[] = [
  {
    id: 1,
    memberId: 'kemediii',
    memberName: '케이엔메디스',
    phoneNumber: '010-1234-5678',
    hospitalName: '서울대학교병원',
    hospitalPhoneNumber: '02-2072-2114',
    doctorName: '김의사',
    procedureDate: '2025-04-10',
    prescriptionNumber: 'P2025041001',
    procedureClassification: '외래',
    procedureName: '일반진료',
    prescriptionCode: 'PC001',
    amount: 50000,
    deductibleAmount: 5000,
    copaymentAmount: 15000,
    benefitRatio: 70,
    userId: 'kemediii',
    businessPartnerName: '벽위 A',
    productName: '에스키토폰오정',
    category: '의약품',
    institution: '다기관',
    type: '제품설명회',
    usageDate: '2025-04-10',
    medicalPersonCount: 1,
    supportAmount: 2000000,
    reportStatus: '미신행'
  },
  {
    id: 2,
    memberId: 'kdqmeq',
    memberName: '케이엔메디스',
    phoneNumber: '010-9876-5432',
    hospitalName: '연세대학교병원',
    hospitalPhoneNumber: '02-2228-5800',
    doctorName: '이의사',
    procedureDate: '2025-04-08',
    prescriptionNumber: 'P2025040801',
    procedureClassification: '입원',
    procedureName: '수술',
    prescriptionCode: 'PC002',
    amount: 150000,
    deductibleAmount: 15000,
    copaymentAmount: 45000,
    benefitRatio: 70,
    userId: 'kdqmeq',
    businessPartnerName: '의원 A',
    productName: '야토건정200mg',
    category: '의약품',
    institution: '단일기관',
    type: '대한검체예비용량의',
    usageDate: '2025-04-08',
    medicalPersonCount: 2,
    supportAmount: 2000000,
    reportStatus: '미신행'
  }
];
