import type { MpPrescriptionReception } from 'api-definitions/MpPrescriptionReception';

export const mockPrescriptionReceptions: Record<number, MpPrescriptionReception> = {
  1: {
    id: 1,
    memberNumber: '1234',
    userId: 'kemediii',
    memberName: '키메디',
    phoneNumber: '010-1234-5678',
    doctor: '홍길동',
    hospital: '서울대학교병원',
    receptionDate: '2025-02-2025-04',
    applicationDate: '2025-04',
    governmentDelegate: '2025-04-09',
    receptionStatus: '파일 다운로드',
    receptionConfirm: true,
    processStatus: 'completed',
    status: 'active',
    sequence: 1
  },
  2: {
    id: 2,
    memberNumber: '1235',
    userId: 'kdqmeq',
    memberName: '케이엠메디슨',
    phoneNumber: '010-2345-6789',
    doctor: '고길동',
    hospital: '연세대세브란스병원',
    receptionDate: '2025-04',
    applicationDate: '2025-04',
    governmentDelegate: '2025-04-09',
    receptionStatus: '파일 다운로드',
    receptionConfirm: false,
    processStatus: 'pending',
    status: 'active',
    sequence: 2
  },
  3: {
    id: 3,
    memberNumber: '3491',
    userId: 'kdqmeq',
    memberName: '케이엠메디슨',
    phoneNumber: '010-3456-7890',
    doctor: '제길동',
    hospital: '삼성서울병원',
    receptionDate: '2025-03',
    applicationDate: '2025-04',
    governmentDelegate: '2025-04-09',
    receptionStatus: '입력완료',
    receptionConfirm: false,
    processStatus: 'processing',
    status: 'active',
    sequence: 3
  },
  4: {
    id: 4,
    memberNumber: '5678',
    userId: 'medipanda',
    memberName: '메디판다',
    phoneNumber: '010-4567-8901',
    doctor: '박의사',
    hospital: '아산병원',
    receptionDate: '2025-04',
    applicationDate: '2025-04',
    governmentDelegate: '2025-04-10',
    receptionStatus: '입력대기',
    receptionConfirm: false,
    processStatus: 'waiting',
    status: 'active',
    sequence: 4
  },
  5: {
    id: 5,
    memberNumber: '9012',
    userId: 'testuser',
    memberName: '테스트유저',
    phoneNumber: '010-5678-9012',
    doctor: '이의사',
    hospital: '강남성심병원',
    receptionDate: '2025-04',
    applicationDate: '2025-04',
    governmentDelegate: '2025-04-11',
    receptionStatus: '검토중',
    receptionConfirm: true,
    processStatus: 'review',
    status: 'active',
    sequence: 5
  }
};
